import {
  Baby,
  BookOpen,
  Camera,
  Car,
  Dumbbell,
  Flower2,
  Footprints,
  Gem,
  Headphones,
  HeartPulse,
  Laptop,
  Palette,
  Shirt,
  Sofa,
  Smartphone,
  Sparkles,
  Speaker,
  UtensilsCrossed,
  Wheat,
  type LucideIcon,
} from "lucide-react";
import type { CategoryId } from "@/types";

export const categoryIcons: Record<CategoryId, LucideIcon> = {
  electronics: Headphones,
  "phones-accessories": Smartphone,
  "computers-tech": Laptop,
  fashion: Shirt,
  "beauty-personal-care": Sparkles,
  "home-living": Sofa,
  "food-groceries": UtensilsCrossed,
  "health-wellness": HeartPulse,
  "baby-kids": Baby,
  "sports-fitness": Dumbbell,
  "books-media": BookOpen,
  "arts-crafts": Palette,
  "jewelry-accessories": Gem,
  automotive: Car,
  "agriculture-farm": Wheat,
};

export const productIcons: Record<string, LucideIcon> = {
  "pulse-anc-headphones": Headphones,
  "resonate-desk-speaker": Speaker,
  "skyeye-4k-drone": Camera,
  "harbor-linen-armchair": Sofa,
  "zenflow-yoga-mat": Flower2,
  "flexfit-training-sneakers": Footprints,
};

export const categoryGradients: Record<CategoryId, string> = {
  electronics: "from-indigo-500 to-violet-500",
  "phones-accessories": "from-blue-500 to-cyan-400",
  "computers-tech": "from-slate-600 to-slate-400",
  fashion: "from-fuchsia-500 to-pink-400",
  "beauty-personal-care": "from-rose-500 to-pink-400",
  "home-living": "from-orange-500 to-amber-400",
  "food-groceries": "from-red-500 to-orange-400",
  "health-wellness": "from-emerald-500 to-teal-400",
  "baby-kids": "from-sky-500 to-blue-400",
  "sports-fitness": "from-green-500 to-lime-400",
  "books-media": "from-yellow-500 to-amber-400",
  "arts-crafts": "from-violet-500 to-purple-500",
  "jewelry-accessories": "from-teal-500 to-emerald-400",
  automotive: "from-zinc-600 to-zinc-400",
  "agriculture-farm": "from-lime-600 to-green-500",
};
